apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "openshift-local-storage"
spec:
  logLevel: Normal
  managementState: Managed
  storageClassDevices:
    - storageClassName: storage-class-http-events
      volumeMode: Filesystem
      fsType: xfs
      # The below must be adjusted to the hardware
      devicePaths:
        - /dev/disk/by-partlabel/httpevent1
        - /dev/disk/by-partlabel/httpevent2