apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud-event-proxy-store
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          # replace this with the name of the node being used
          - node1.example.com

