apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-event-proxy-store
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Mi
  accessModes:
  - ReadWriteOnce

