apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: amq-router
  name: amq-router
  namespace: amq-router
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: amq-router
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amq-router
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - local
      containers:
        - env:
            - name: QDROUTERD_CONF
              value: /opt/router/qdrouterd.conf
          image: quay.io/interconnectedcloud/qdrouterd:latest
          imagePullPolicy: Always
          name: amq-router
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/router
              name: router-config
              readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
        - configMap:
            defaultMode: 420
            name: amq-router
          name: router-config