apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-bare-metal-events
resources:
- service-account.yaml
- roles.yaml
- service.yaml
- route.yaml
- deployment.yaml
replicas:
- count: 1
  name: hw-event-proxy
secretGenerator:
- literals:
  - username=root
  - password=calvin
  - hostaddr=10.16.231.83
  name: redfish-basic-auth
  type: Opaque
images:
- name: cloud-event-sidecar
  newName: quay.io/redhat-cne/cloud-event-proxy
  newTag: release-4.12
- name: hw-event-proxy
  newName: quay.io/redhat-cne/hw-event-proxy
  newTag: release-4.12
