apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-bare-metal-events
resources:
- service-account.yaml
- roles.yaml
- service.yaml
- deployment.yaml
images:
- name: cloud-event-consumer
  newName: quay.io/redhat-cne/cloud-event-consumer
  newTag: release-4.14
- name: cloud-event-sidecar
  newName: quay.io/redhat-cne/cloud-event-proxy
  newTag: release-4.14
